/* eslint-disable @typescript-eslint/no-explicit-any */

declare module '*page.js' {
  const whatever: any;
  export default whatever;
}

// Catch-all for generated layout imports
declare module '*layout.js' {
  const whatever: any;
  export default whatever;
}

declare module '*src/app/*/page.js' {
  import type { ComponentType } from 'react';
  const Page: ComponentType<any>;
  export default Page;
}

declare module '*src/app/*/page' {
  import type { ComponentType } from 'react';
  const Page: ComponentType<any>;
  export default Page;
}

// Also match paths without the `src/` prefix (Next/Turbopack sometimes emits '../../../app/..')
declare module '*app/*/page.js' {
  import type { ComponentType } from 'react';
  const Page: ComponentType<any>;
  export default Page;
}

declare module '*app/*/page' {
  import type { ComponentType } from 'react';
  const Page: ComponentType<any>;
  export default Page;
}

// layout modules
declare module '*src/app/layout.js' {
  import type { ComponentType } from 'react';
  const Layout: ComponentType<any>;
  export default Layout;
}

declare module '*app/layout.js' {
  import type { ComponentType } from 'react';
  const Layout: ComponentType<any>;
  export default Layout;
}

// Match nested layouts like app/my/layout.js
declare module '*src/app/*/layout.js' {
  import type { ComponentType } from 'react';
  const Layout: ComponentType<any>;
  export default Layout;
}

declare module '*app/*/layout.js' {
  import type { ComponentType } from 'react';
  const Layout: ComponentType<any>;
  export default Layout;
}

declare module '*src/app/*/layout' {
  import type { ComponentType } from 'react';
  const Layout: ComponentType<any>;
  export default Layout;
}

declare module '*app/*/layout' {
  import type { ComponentType } from 'react';
  const Layout: ComponentType<any>;
  export default Layout;
}

// Fallback for other .js imports generated by Next/Turbopack
declare module '*page.js' {
  const whatever: any;
  export default whatever;
}
